### ISSUE TITLE
WhereChecker fails to compare Dates using direct equality (other operators work) and unequal dates pass the check

### ISSUE THREAD

**Issue by The-MAZZTer** [ujjwalguptaofficial/JsStore#199]
There are two problems here;

1. When invalid keywords are used in a where object where in/like/operators are expected, invalid keywords are ignored and the where condition always passes. An error should be raised instead..
2. Date objects are mistaken for where object (in/like/operators).

Note 2 does NOT impact if you use the where operator syntax since then the Date objects are compared appropriately. So it's only an issue if you're doing direct equality with Dates

Error in jsstore.worker.js line 2179. Here is the relevant code:

            if (typeof columnValue === 'object') {

This if check is trying to detect the where in/like/operators logic, but Dates also pass this check! Remember pretty much everything that is not a primitive is an object in JS!

Related bug, this user seemed to have the same problem: https://github.com/ujjwalguptaofficial/JsStore/issues/189

Use case:

I have a field called "read" in my items that records the Date the user read an item. I want to expire it some time after the user has read it, so I want to track the time they did. However I also want to track if they read the item or not. So I use the special value `new Date(0)` to indicate the item is unread; (null value does not seem to be permitted by indexeddb). Thus I would want to be able to query for `new Date(0)` to return all unread objects and ignore read ones.

Example:

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=update(%7B%0A%20%20%20%20in%3A%20%22Orders%22%2C%0A%20%20%20%20set%3A%20%7B%0A%20%20%20%20%20%20%20%20orderDate%3A%20new%20Date(%222000-01-01T00%3A00%3A00.000Z%22)%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20orderId%3A%2010250%0A%20%20%20%20%7D%0A%7D)%3B%0A%0Aselect(%7B%0A%20%20%20%20from%3A%20%22Orders%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20shipperId%3A%202%2C%0A%20%20%20%20%20%20%20%20orderDate%3A%20new%20Date(%222000-01-01T00%3A00%3A00.000Z%22)%0A%20%20%20%20%7D%0A%7D)%3B

Expected one record, you can see there are more records returned.

BTW all the dates in your demo database are the same, which is why you haven't noticed this issue, I recommend putting some variety in there!

My recommended fix is to replace the `check` function with this:

      WhereChecker.prototype.check = function (rowValue) {
        this.status = true;

        if (this.checkFlag === true) {
          for (var columnName in this.where) {
            if (!this.status) {
              break;
            }

            var columnValue = this.where[columnName];
            var recordValue = rowValue[columnName];
            if (columnValue.constructor.name === "Date") {
              columnValue = columnValue.valueOf();
            }
            if (recordValue.constructor.name === "Date") {
              recordValue = recordValue.valueOf();
            }

            if (typeof columnValue === 'object') {
              for (var key in columnValue) {
                if (!this.status) {
                  break;
                }

                switch (key) {
                  case QUERY_OPTION.In:
                    this.status = this.checkIn(columnName, recordValue);
                    break;

                  case QUERY_OPTION.Like:
                    this.status = this.checkLike_(columnName, recordValue);
                    break;

                  case QUERY_OPTION.Regex:
                    this.checkRegex(columnName, recordValue);
                    break;

                  case QUERY_OPTION.Between:
                  case QUERY_OPTION.GreaterThan:
                  case QUERY_OPTION.LessThan:
                  case QUERY_OPTION.GreaterThanEqualTo:
                  case QUERY_OPTION.LessThanEqualTo:
                  case QUERY_OPTION.NotEqualTo:
                    this.status = this.checkComparisionOp_(columnName, recordValue, key);
                    break;
                }
              }
            } else {
              this.status = columnValue === recordValue;
            }
          }
        }

        return this.status;
      };

I added the Date checks on the top and cache the real record value in recordValue so I can modify it before passing it through. These changes turn the dates into numbers which the code can already handle fine (Dates will not pass === checks when they have the same value). Comparing the constructor names is done since you can have multiple Date classes thanks to having multiple execution contexts (eg web worker, frames) each with their own Date object, so a simple `instanceof `check could fail; depends how the data is being marshalled.

Further changes will be needed to support the IN property I think. Probably something like:

      WhereChecker.prototype.checkIn = function (column, value) {
        return this.where[column][QUERY_OPTION.In].find(function (val) {
          if (val.constructor.name === "Date") {
            val = val.valueOf();
          }
          return val === value;
        }) != null;
      };

**Comment by ujjwalguptaofficial** [comment]
noted, will work on this.

**Comment by ujjwalguptaofficial** [comment]
Thanks @The-MAZZTer for such a detailed explanation. I have fixed this in new version - 3.13.2 . Please have a look and let me know. I have also updated idbstudio, so above link can be also used for testing.

**Comment by The-MAZZTer** [comment]
Dates still don't compare properly; equality won't work to compare two Date objects:

    > new Date(0) === new Date(0)
    < false

jsstore.worker.js:2214, 2224, and 2263 compares dates with === or !== which won't work.

The getDataType function looks ok but WhereChecker.prototype.check isn't using it yet!

The three lines using === and !== compares will need special logic for Dates (or Dates need to be converted to numbers before those checks).

I made these changes locally which work for me.

Before:

            if (getDataType(columnValue) === 'object') {
              for (var key in columnValue) {
                if (!this.status) {
                  break;
                }

                switch (key) {
                  case QUERY_OPTION.In:
                    this.status = this.checkIn(columnName, rowValue[columnName]);
                    break;

                  case QUERY_OPTION.Like:
                    this.status = this.checkLike_(columnName, rowValue[columnName]);
                    break;

                  case QUERY_OPTION.Regex:
                    this.checkRegex(columnName, rowValue[columnName]);
                    break;

                  case QUERY_OPTION.Between:
                  case QUERY_OPTION.GreaterThan:
                  case QUERY_OPTION.LessThan:
                  case QUERY_OPTION.GreaterThanEqualTo:
                  case QUERY_OPTION.LessThanEqualTo:
                  case QUERY_OPTION.NotEqualTo:
                    this.status = this.checkComparisionOp_(columnName, rowValue[columnName], key);
                    break;

                  default:
                    this.status = false;
                }
              }
            } else {
              this.status = columnValue === rowValue[columnName];
            }

After:

switch(getDataType(columnValue)) {
              case DATA_TYPE.Object:
                for (var key in columnValue) {
                  if (!this.status) {
                    break;
                  }
  
                  switch (key) {
                    case QUERY_OPTION.In:
                      this.status = this.checkIn(columnName, rowValue[columnName]);
                      break;
  
                    case QUERY_OPTION.Like:
                      this.status = this.checkLike_(columnName, rowValue[columnName]);
                      break;
  
                    case QUERY_OPTION.Regex:
                      this.checkRegex(columnName, rowValue[columnName]);
                      break;
  
                    case QUERY_OPTION.Between:
                    case QUERY_OPTION.GreaterThan:
                    case QUERY_OPTION.LessThan:
                    case QUERY_OPTION.GreaterThanEqualTo:
                    case QUERY_OPTION.LessThanEqualTo:
                    case QUERY_OPTION.NotEqualTo:
                      this.status = this.checkComparisionOp_(columnName, rowValue[columnName], key);
                      break;
  
                    default:
                      this.status = false;
                  }
                }
                break;
              case DATA_TYPE.DateTime:
                this.status = columnValue.valueOf() === rowValue[columnName].valueOf();
                break;
              default:
                this.status = columnValue === rowValue[columnName];
                break;
            }

Before:

      WhereChecker.prototype.checkIn = function (column, value) {
        return this.where[column][QUERY_OPTION.In].find(function (val) {
          return val === value;
        }) != null;
      };

      WhereChecker.prototype.checkComparisionOp_ = function (column, value, symbol) {
        var compareValue = this.where[column][symbol];

        /* ... */
      };

After:

      WhereChecker.prototype.checkIn = function (column, value) {
        if (value instanceof Date) {
          value = value.valueOf();
        }

        return this.where[column][QUERY_OPTION.In].find(function (val) {
          if (val instanceof Date) {
            val = val.valueOf();
          }

          return val === value;
        }) != null;
      };

      WhereChecker.prototype.checkComparisionOp_ = function (column, value, symbol) {
        var compareValue = this.where[column][symbol];
        if (compareValue instanceof Date) {
          compareValue = compareValue.valueOf();
        }
        if (value instanceof Date) {
          value = value.valueOf();
        }

        /* ... */
      }

IDBStudio Example (expect one row returned, 0 actually returned):

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Orders%22%2C%0A%20%20%20%20where%3A%7B%0A%20%20%20%20%20%20%20%20employeeId%3A%205%2C%0A%20%20%20%20%20%20%20%20orderDate%3A%20new%20Date(%222021-03-02T17%3A06%3A48.526Z%22)%0A%20%20%20%20%7D%0A%7D)%3B%0A

If you remove the employeeId you'll see records, including the one that should be returned.

**Comment by ujjwalguptaofficial** [comment]
right, i was thinking that === will work for two date. I will correct this.

**Comment by ujjwalguptaofficial** [comment]
@The-MAZZTer suggested changes has been done. Please check in new version -  3.13.5
