### ISSUE TITLE
InvalidAccessError in ie for jsstore.min.js

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#45]
Hi,

All my other scripts are accessible and working fine.But not jsstore.min.js in ie 11.Help me to fix it

thanks

**Comment by ujjwalguptaofficial** [comment]
This issue is happening in v2 right ?

**Comment by ujjwalguptaofficial** [comment]
Also please add a query example to generate the issue.

**Comment by kamalakkanni** [comment]
no,I am using v1 only.I tried to change it to v2.But I got webworker
error.So I revert my code.so it is v1.

**Comment by ujjwalguptaofficial** [comment]
I am sorry but I cant work on v1 now. There were many bugs and improvements which were fixed in v2. And most importantly we support migration from v1. 

So please update to v2. If you are getting any issue like the one you mentioned about web worker error please add another issue like - "Getting problem when migrating from v1 to v2". I will surely help you.

The chances may be that what ever issue you are getting that may be you are getting is fixed in v2.

Thanks

**Comment by kamalakkanni** [comment]
Hi,this is happening at v2 also

**Comment by ujjwalguptaofficial** [comment]
Ok please add a sample query to generate the issue.

Thanks

**Comment by kamalakkanni** [comment]
return this._connection.select<Article>({
      from: this.table,
      distinct: true
    });

**Comment by ujjwalguptaofficial** [comment]
Lets talk on gitter - https://gitter.im/JsStore . Please join group and ping.

**Comment by ujjwalguptaofficial** [comment]
@kamalakkanni - issue if fixed in 2.1.0. Please let me know.

Thanks

**Comment by kamalakkanni** [comment]
Not yet fixed.It gives "Assignment to read-only properties is not allowed in strict mode" in jsstore.worker.js .
so indexeddb is also not gettingcreated

**Comment by ujjwalguptaofficial** [comment]
Please tell us the ie and windows version.

**Comment by kamalakkanni** [comment]
ie11 and windows 10

**Comment by UmeshGowda** [comment]
`private getDatabase() {

    const tblKpi: ITable = {
      name: 'kpi',
      columns: [{
        name: 'id',
        primaryKey: true,
        autoIncrement: true
      },
      {
        name: 'productName',
        dataType: DATA_TYPE.String,
        notNull: true
      },
      {
        name: 'location',
        dataType: DATA_TYPE.String,
        notNull: true
      },
      {
        name: 'vendor',
        dataType: DATA_TYPE.String,
        notNull: true
      },
      {
        name: 'severity',
        dataType: DATA_TYPE.String,
        notNull: true
      },
      {
        name: 'total',
        dataType: DATA_TYPE.String,
        notNull: true
      }
      ]
    }

    const dataBase: IDataBase = {
      name: this.dbname,
      tables: [tblKpi]
    };
    return dataBase;
  }


this.connection.select({
      from: "kpi",
      aggregate: {
          sum: "total"
      }
  });`

hello am trying to run the above aggregate query but am getting the below error. can anyone please help in this 



Argument of type '{ from: string; aggregate: { sum: string; }; }' is not assignable to parameter of type 'ISelect'.
  Types of property 'aggregate' are incompatible.
    Type '{ sum: string; }' is not assignable to type 'IAggregate'.
      Types of property 'sum' are incompatible.
        Type 'string' is not assignable to type 'any[]'.

**Comment by ujjwalguptaofficial** [comment]
@UmeshGowda  - Please come to this issue - https://github.com/ujjwalguptaofficial/JsStore/issues/50 . Since the issue you are having is not realated to this , we shouldn't talk here.

**Comment by kakugiki** [comment]
I got the same InvalidAccessError error with Edge on Windows 10 Pro, no further error log. Web api response was inserted to idb. 

![image](https://user-images.githubusercontent.com/21064307/41171399-6814b4a6-6b1e-11e8-861e-0f152ff178c1.png)

**Comment by kamalakkanni** [comment]
yes it is inserted.But not fetching data.

**Comment by ujjwalguptaofficial** [comment]
Hey guys - I tried this in ie and not getting this any issue .

![image](https://user-images.githubusercontent.com/10938615/41328344-33b7d9c0-6ee5-11e8-9bde-6851cc2f1ef1.png)

 Not sure but probably its bug in ie and has been fixed in update. My Ie version is - Microsoft Edge 41.16299.248.0

**Comment by kamalakkanni** [comment]
its working fine.thanks

**Comment by kakugiki** [comment]
Your demo works fine, but my app still has some issues. I guess it's something specific to my app not Edge in general. Thanks for fixing the issue.

**Comment by kamalakkanni** [comment]
In ie it shows loading only and gives below console error


object Error]{description: "'Promise' i...", message: "'Promise' i...", name: "ReferenceEr...", number: -2146823279, stack: "ReferenceEr..."}

**Comment by kamalakkanni** [comment]
Hi,

Any updation

Thanks

**Comment by ujjwalguptaofficial** [comment]
no , I am not able to reproduce the issue. If you can help me reproducing that would be great.

**Comment by kamalakkanni** [comment]
What I have to do

**Comment by ujjwalguptaofficial** [comment]
I have asked you but you didn't answer. Are you able to load idbstudio in your browser - https://ujjwalguptaofficial.github.io/idbstudio/ ?

Let me know.

**Comment by kamalakkanni** [comment]
I already replied its workign fine in microsoft edge and not in ie.
In ie it shows loading  and gives below console error

object Error]{description: "'Promise' i...", message: "'Promise' i...", name: "ReferenceEr...", number: -2146823279, stack: "ReferenceEr..."}

"'Promise' is undefined"

**Comment by ujjwalguptaofficial** [comment]
ok cool. I thought that was about your apps. I think if promise is not supported then it wont support idb. Check out these links - 
1. https://github.com/github/fetch/issues/114 
2. https://stackoverflow.com/questions/29703520/why-does-internet-explorer-11-not-detect-indexeddb

But if you think indexeddb will work irrespective of promise support, then use some polyfills for promise and see if its working. Good luck with the experimentation and let me know.

**Comment by ujjwalguptaofficial** [comment]
According to this website https://caniuse.com/#feat=indexeddb  - there is partial support of indexeddb which means there will be no of bugs. So I would say just check if promise is defined and if not do not use idb. 

There will be very less people who will be using ie11 but yeah I understand we want to support for every browsers. In that case - you will have to include the pollyfill.

**Comment by kamalakkanni** [comment]
Thanks and sorry for the late response .Below is my polyfill.ts

/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es7/symbol';
import 'core-js/es7/object';

import 'core-js/es7/math';
import 'core-js/es7/string';

import 'core-js/es7/array';

import 'core-js/es7/map';
import 'core-js/es7/weak-map';
import 'core-js/es7/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/**
 * Required to support Web Animations `@angular/animation`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
// import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
// import 'intl/locale-data/jsonp/en';

**Comment by kamalakkanni** [comment]
In this file,I included import { polyfill } from 'es6-promise'; polyfill(); as per the link github/fetch#114 what u send.But not yet solved

**Comment by ujjwalguptaofficial** [comment]
Check out this package -  https://www.npmjs.com/package/promise-polyfill . 
import it where the app is registered or bootstrapped. 

`import 'promise-polyfill/src/polyfill';`

Let me know if this helps.

**Comment by kamalakkanni** [comment]
ok.thank you

**Comment by ujjwalguptaofficial** [comment]
@kamalakkanni - check out these two polyfill 
* https://github.com/ujjwalguptaofficial/JsStore/blob/master/src/test/scripts/findindex_polyfill.js
* https://github.com/ujjwalguptaofficial/JsStore/blob/master/src/test/scripts/find_polyfill.js

Download both polyfill and add it your project, after that you will be able to run everything in ie. If not , feel free to reopen the issue and have more conversation. I am sorry for late reply, I was completely busy with other things.

Thanks

**Comment by kamalakkanni** [comment]
Thanks,I will try and let u know
