### ISSUE TITLE
Error inside service worker - self.postMessage is not a function

### ISSUE THREAD

**Issue by llioor** [ujjwalguptaofficial/JsStore#60]
I'm using jsStore in my service worker and I have this error:
`Uncaught TypeError: self.postMessage is not a function`

First, there is no place on the web which shows how to initialize the jsStore in a service worker. If someone can give me a link it will be nice.

Second, I have this error and I'd like to solve it. This is what I'm doing:
```
if ('function' === typeof importScripts) {
  importScripts('https://cdn.jsdelivr.net/npm/jsstore@2.2.1/dist/jsstore.min.js')
  importScripts('https://cdn.jsdelivr.net/npm/jsstore@2.2.1/dist/jsstore.worker.min.js')
}

var SERVER_PATH = '<path to my API server>'

var dbTableName = 'client_db'
var dbSupport = false
var connection = new JsStore.Instance()
connection.isDbExist(dbTableName).then(function(isExist) {
  if (isExist) {
    connection.openDb(dbTableName)
    dbSupport = true
  }
})
```
I got this error:
```
Uncaught TypeError: self.postMessage is not a function
    at e.returnResult_ (jsstore.worker.min.js:6)
    at r (jsstore.worker.min.js:6)
    at Function.<anonymous> (jsstore.worker.min.js:6)
    at Object.OnSuccess (jsstore.worker.min.js:6)
    at Function.e.onQueryFinished (jsstore.worker.min.js:6)
    at e.onSuccess (jsstore.worker.min.js:6)
    at e.returnResult (jsstore.worker.min.js:6)
    at t.r [as onSuccess] (jsstore.worker.min.js:6)
    at o.onTransactionCompleted_ (jsstore.worker.min.js:6)
    at IDBTransaction.e.createTransaction._transaction._transaction.oncomplete (jsstore.worker.min.js:6)
```

Thank you in advance for the help and than you for the amazing package.
Leo.

**Comment by ujjwalguptaofficial** [comment]
Thanks for the compliment @llioor . It should not happen, but I have not tried it in service worker, I will create an example for this and let you know.

**Comment by ujjwalguptaofficial** [comment]
Actually there is an issue, i just found after reading your case. I will solve it and let you know. 

Thanks

**Comment by ujjwalguptaofficial** [comment]
@llioor - the issue is fixed in v 2.2.2. Here is cdn url - https://www.jsdelivr.com/package/npm/jsstore.

Please check and let me know. And if you could create an example for service worker and send a pr that would be very helpful.

Thanks

**Comment by llioor** [comment]
Hi @ujjwalguptaofficial , thank you for the quick response!
I saw ur new version 2.2.2 and I still see the same error...
Check print screen:
![sw-jsstore](https://user-images.githubusercontent.com/6999073/42799370-4c1abb56-89a0-11e8-8a70-3adbe1f66ca5.png)

**Comment by ujjwalguptaofficial** [comment]
Oho OK, I will dig more.

**Comment by ujjwalguptaofficial** [comment]
There was a minor issue, I have tested now and fixed in v 2.2.3. I have also added the example - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/service%20worker.  Please check and let me know.

Thanks

**Comment by llioor** [comment]
Thank you very much!
Regarding the "code sample" (PR) you can use the example I mentioned above.. this is classic way to use jsStore in a service worker.
What's important here is to use importScripts function which supported in service worker.
