### ISSUE TITLE
How to create Instance without web worker

### ISSUE THREAD

**Issue by Doc1027** [ujjwalguptaofficial/JsStore#63]
Hi I am trying to use your lib. I must support IE / Edge. IE does not have native Promise support and I still can't get it to work with promise-polyfill. My solution was going to be use your lib without a  webworker which your dox state is supported however, when I try to new up an Instance without passing new Webworker... in the ctor I get the following error: JsStoreWorker is not defined. What should I do??

**Comment by ujjwalguptaofficial** [comment]
Hi 

I have added an example for using without web worker. Check it out here - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/without%20web%20worker

**Comment by ujjwalguptaofficial** [comment]
My guess is - you are not including jsstore.worker . jsstore.worker is a file - which needed to be supplied either for worker or not worker. So if u are using worker then supply the file in Worker constructor and if not in worker then include the file. Hope this makes sense.

**Comment by Doc1027** [comment]
Thanks for the reply. Following the typescript example I have this import in my service: 
import * as workerPath from "file-loader?name=scripts/[name].[hash].js!jsstore/dist/jsstore.worker.js"; 

Is that not enough? Or am I misunderstanding you?

**Comment by Doc1027** [comment]
Also, in a worker.d.ts file:
declare module "file-loader?name=scripts/[name].[hash].js!*" {
    const value: string;
    export = value;
   }

**Comment by ujjwalguptaofficial** [comment]
Actually workerpath returns the path of file - which is supplied in Worker constructor. But for without worker we need the jsstore.worker file to be in global context, so that JsStoreWorker is defined. 

currently JsStore.worker.js is not available as commonjs module, which means importing it wont work. So right now the only way is to include the script in html file.

I will build the worker file as common module and let you know.

**Comment by ujjwalguptaofficial** [comment]
Hi

The problem is resolved in v 2.3.1 .  I have also added an example. Take a look at it - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/ts%20without%20worker

Hope this works for you.

Thanks

**Comment by Doc1027** [comment]
Hi. Thanks again for your attention. I will upgrade, try out the fix and report back. Thanks again.

**Comment by Doc1027** [comment]
Ok the upgrade worked for running without a webworker. Unfortunately I still cannot get this to run in IE 11 / Edge. It's throwing DOMException "InvalidAccessError". Also in Chrome, I notices that "cursorOpenRequest.onsuccess" in your jsstore.worker.commonjs2.js file is consuming alot of memory. I thank you in advance for your efforts.

**Comment by ujjwalguptaofficial** [comment]
Hi , Let's close this issue And fire another issue. There is a ie/edge issue - https://github.com/ujjwalguptaofficial/JsStore/issues/45, check the comments if that helped otherwise you can reopen and add more details.

You can add another issue for memory consumption issue.

Thanks

**Comment by Doc1027** [comment]
Ok Will Do. Thanks again.
